### ISSUE TITLE
[Girish] Completed Assignment 3

### ISSUE THREAD

**Issue by GirishRawat** [mobilespace/exploring-react-native#2]
https://github.com/GirishRawat/exploring-react-native

**Comment by mobilespace** [comment]
@GirishRawat Looks good. Please update the TODO on your readme: https://github.com/GirishRawat/exploring-react-native#todo

**Comment by Monte9** [comment]
@GirishRawat I have added part 2 of the assignment. Please check it out here: https://github.com/mobilespace/exploring-react-native#todo

Closing this issue for now. Please reopen it once you have completed the second part as well.
